### ISSUE TITLE
Implementing audit logging to database - Quick Search Error

### ISSUE THREAD

**Issue by aq94** [i2group/analyze#63]
Hi Team, 

I previously raised an issue regarding our team's implementation of the audit logging feature (database) as per - https://github.com/i2group/analyze/issues/61 

Further responses to this issue were captured via case 00003472 and APAR PO09684.

Our team has since updated to EIA 2.4.1 in another one of our test environments following the same steps discussed in issue 61.

There still appears to be the same issue with our audit logging function specific to quick searches where the logs are being captured twice (please see excel sheet attached, note that EVENT_TIME has two records with a few milliseconds apart).

The other functions (expand, record retrieval and visual query) are now all functioning as  expected.

Could you please confirm if the quick search duplicates were resolved as part of the previous fix or if this is a persistent issue?

Thanks,
Adam
[GitHub Ticket Issues - 24-02-22.xlsx](https://github.com/i2group/analyze/files/8128769/GitHub.Ticket.Issues.-.24-02-22.xlsx)

**Comment by Colvin-Cowie-i2** [comment]
Hi Adam,

I see it wasn't noted in #61 but it should have been communicated directly at the time; multiple search events are generated because the client makes multiple requests to the search endpoints. If you call `getServiceMethodName()` on the audit event then you can see that the calls are to two different search endpoints (/results and /summary), so if you include that in your output you will be able to distinguish them.

Regards,
Colvin

**Comment by aq94** [comment]
Hi Colvin,

Thanks for confirming the above - we'll factor this into consideration and it sounds like we are good to go then.

Cheers,
Adam
