### ISSUE TITLE
Login, Logout & Acceptance audit function

### ISSUE THREAD

**Issue by hillijim** [i2group/analyze#69]
Are you able to include login, logout and privacy agreement acceptance in the database audit example?

**Comment by Anthony-Johnson-i2** [comment]
Hi Jim 

Yes, you can, if you are on a new enough version of your deployed i2 Analyze and the corresponding version of Developer Essentials for i2 Analyze.

The following events all say  'Since 13.0' which means, they will only be usable if you are using the Q2 2022 i2 Analyze 4.4.0 or above and the corresponding Developer Essentials for i2 Analyze v4.4.0.

If you have these versions, then you can add to your example code so that it can get the information you want from:

https://i2group.github.io/analyze/docs/com/i2group/disco/audit/ILoginAuditEvent.html

https://i2group.github.io/analyze/docs/com/i2group/disco/audit/ILogoutAuditEvent.html

https://i2group.github.io/analyze/docs/com/i2group/disco/audit/IPrivacyAgreementAuditEvent.html

You also need to make sure this is set to true in your code.
https://i2group.github.io/analyze/docs/com/i2group/disco/audit/spi/IAuditLogger.html#isAuthenticationAuditEnabled()

You then need to decide what you want to record from these events and add a table to your database designed as you see fit to record the data from the new events you are using.

The default example is only for reference, to get you started,  and how much you get your version of that to actually do is completely up to you.

I recognise your name Jim, from a conversation that Chee Mun How is currently having with a customer so it would be best to continue there, rather than try to maintain multiple streams of information.

Cheers

**Comment by hillijim** [comment]
Understood Tony, it was more a question for your team in relation to customer experience. Login, logout I would have thought were fundamental. Saves the customer having to battle through themselves and work it out and/or rely on support services from i2 Group

**Comment by Anthony-Johnson-i2** [comment]
Hi Jim, the example code is just that, an example, so should not be used in a production deployment without modification to better suit its intended role for the customer, but as you say these are options that would most likely be always wanted. 

When the example code was written these options did not exist or I expect we would have included them. 

Cheers.

**Comment by Anthony-Johnson-i2** [comment]
Hi Jim 
I got the example working for the three new events you are interested in on my test machine and made the details available to be sent on to you by eMail via Chee Mun so that you can refer to them to help you get yours going.
Cheers
